### ISSUE TITLE
Feature: User can edit an outfit

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ice-time#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit all previously added information in their outfit entry.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "edit" button when viewing details for an outfit in order to edit information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue10m](https://user-images.githubusercontent.com/106547566/200661794-b699a3c4-091e-4dd1-a479-b433375d1944.PNG)
![fpissue10d](https://user-images.githubusercontent.com/106547566/200661796-cccd2af8-2cca-4dd8-8d55-f7f5bfc553f5.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a PUT request to update the outfits table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to go to the edit outfits page when the edit button is clicked. 
- [x] Update component to send a fetch request when submitting form from the edit-outfits page to update the selected outfit.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
