### ISSUE TITLE
Feature: User can delete an outfit

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ice-time#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an outfit entry to remove it from their outfits list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "delete entry" button while editing an outfit in order to permanently remove it from their outfits list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue11m](https://user-images.githubusercontent.com/106547566/200662489-bbc95247-deea-4d4c-b095-46ef36845e20.PNG)
![fpissue11d](https://user-images.githubusercontent.com/106547566/200662492-d9261966-f0d0-4260-b181-f7fca9215576.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to delete an outfit at a given outfitId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to open up the delete modal when the delete outfit button is pressed.
- [x] Update component to send a fetch request to delete the current outfit when the delete button in pressed in the modal.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
