### ISSUE TITLE
Feature: User can view an info page about the site

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ice-time#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the About page to see some information about the site.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the About link in the nav bar in order to view some information about the site.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue15m](https://user-images.githubusercontent.com/106547566/200668554-701fe821-3be8-41ff-b758-56bf753113e1.PNG)
![fpissue15d](https://user-images.githubusercontent.com/106547566/200668559-910b4bd6-988a-429d-a448-eb54876cd443.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to display info on the About page for the site.
- [x] Update component to route to the about page when clicking on the About link.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
