### ISSUE TITLE
Feature: User can view a list of scheduled events

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ice-time#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change the view of events from calendar to list view.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the icon to switch to list view. This will show all upcoming events in a list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue2m](https://user-images.githubusercontent.com/106547566/200650020-5550ac3f-ed93-4690-bdf2-d505d13a9889.PNG)
![fpissue2d](https://user-images.githubusercontent.com/106547566/200650025-0d384eb6-8f55-4de0-bc94-d46b69b61d67.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to display the Upcoming page when clicking on the list icon on the Home page.
- [x] Update component to send upcoming dates to EventTile component using the value prop.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
