### ISSUE TITLE
Feature: User can view details for an outfit

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/ice-time#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view individual details for each saved outfit.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on each outfit tile in order to view a page with all of its details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue9m](https://user-images.githubusercontent.com/106547566/200661446-3ac2e7d9-783f-419c-8be5-cb72c05b853f.PNG)
![fpissue9d](https://user-images.githubusercontent.com/106547566/200661449-f29b7e1d-b7a9-4059-a0b3-aced8c1b5376.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a get request for outfits by outfitId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to view outfit descriptions
- [x] Update view-outfit component to link to view outfit descriptions component, passing the outfit Id as a prop. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
